name: CI
run-name: Run integration
on:
  pull_request:
    branches: [dev]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo '${{ toJSON(github) }}'
      - uses: actions/setup-python@v4
        with:
            python-version: '3.10' 
      - run: pip install -r src/requirements/local.txt
      - run: flake8
  
      
